#!/bin/bash

# Script to update python packages.

LOG_FILE="$HOME/.pymaintenance_log"

echo -n > "$LOG_FILE"
# pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip3 install -U --user | tee -a "$LOG_FILE"
python3 -m pip install --user --upgrade pip
pip3 install --user -U $(pip3 list -o --format=freeze | awk '{split($0, a, "=="); print a[1]}') | tee -a "$LOG_FILE"
